# Generated by Django 5.2.14 on 2026-05-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["rank", "-rating", "title"],
                "verbose_name": "电影库",
                "verbose_name_plural": "电影库",
            },
        ),
    ]
