# Generated by Django 5.2.14 on 2026-05-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_douban_weekly_reputation_movie"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doubanchartmovie",
            options={
                "ordering": ["rank", "title"],
                "verbose_name": "豆瓣电影排行榜",
                "verbose_name_plural": "豆瓣电影排行榜",
            },
        ),
        migrations.AlterModelOptions(
            name="doubanweeklyreputationmovie",
            options={
                "ordering": ["rank", "title"],
                "verbose_name": "豆瓣一周口碑榜",
                "verbose_name_plural": "豆瓣一周口碑榜",
            },
        ),
        migrations.AlterModelOptions(
            name="upcomingmovienews",
            options={
                "ordering": ["event_date", "sort_order", "title"],
                "verbose_name": "近期片讯",
                "verbose_name_plural": "近期片讯",
            },
        ),
    ]
