# Generated by Django 5.2.14 on 2026-05-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0002_recommendationfeedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recommendationfeedback",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "推荐反馈",
                "verbose_name_plural": "推荐反馈",
            },
        ),
        migrations.AlterModelOptions(
            name="recommendationresult",
            options={
                "ordering": ["rank_order"],
                "verbose_name": "推荐结果",
                "verbose_name_plural": "推荐结果",
            },
        ),
    ]
