# Generated by Django 5.2.14 on 2026-05-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_usersession_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ratingform",
            options={
                "ordering": ["category"],
                "verbose_name": "评分表",
                "verbose_name_plural": "评分表",
            },
        ),
        migrations.AlterModelOptions(
            name="ratingformmovie",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "评分表电影",
                "verbose_name_plural": "评分表电影",
            },
        ),
        migrations.AlterModelOptions(
            name="userrating",
            options={
                "ordering": ["created_at"],
                "verbose_name": "用户偏好评分",
                "verbose_name_plural": "用户偏好评分",
            },
        ),
        migrations.AlterModelOptions(
            name="usersession",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "用户推荐会话",
                "verbose_name_plural": "用户推荐会话",
            },
        ),
    ]
